language: c++

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      sudo: false

notifications:
  email: false

before_install:
  - ./.travis-`uname`.sh
  - pip3 install --user neovim

script:
  - ./test/all.sh
