language: c++

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++
            - gdb
            - lldb-5.0
            - python3-dev
            - python3-pip

    - os: osx
      sudo: false

notifications:
  email: false

before_install:
  - ./.travis-`uname`.sh
  - pip3 install --user neovim

script:
  - ./test/all.sh
