language: c++
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++
            - gdb
            - lldb-5.0
            - python3-dev
            - python3-pip
            - lua5.1
            - liblua5.1-0-dev

    - os: osx

notifications:
  email: false

before_install:
  - ./.travis-`uname`.sh
  - pip3 install --user neovim
  - ./install.sh

script:
  - ./test/all.sh -v
