language: c++

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      sudo: required

notifications:
  email: false

before_install:
  - ./.travis-`uname`.sh
  - sudo pip3 install neovim

script:
  - ./test/all.sh
