language: c++
sudo: required
dist: trusty
notifications:
  email: false

before_install:
  - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository ppa:neovim-ppa/unstable -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq upgrade
  - sudo apt-get install -y g++ gdb lldb neovim
  - sudo apt-get install python-dev python-pip python3-dev python3-pip

  - sudo pip2 install neovim
  - sudo pip3 install neovim

script:
  - ./test/all.sh
