name: Test

on: [push, pull_request]

env:
  TERM: xterm

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    runs-on: ${{ matrix.os }}

    timeout-minutes: ${{ (matrix.os == 'windows-latest' && 15) || 7 }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python utils/setup-testenv.py
        python -m pip install --upgrade pip
        python -m pip install pynvim
        python -m pip install pytest pytest-timestamper

    - name: Platform-specific dependencies
      if: runner.os == 'Windows'
      run: |
        python -m pip install pywinpty

    - name: Run tests
      run: |
        python ./test/all.py

    - name: Archive script logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs-${{ matrix.os }}
        path: test/*.log
